name: Pyjama
main: dheam.pyjama.paper.PaperPlugin
version: ${version}
api-version: '26.1'
folia-supported: true
author: dheam
description: Pyjama plugin.

softdepend:
  - MiniPlaceholders

permissions:
  pyjama.*:
    description: Grants access to all Pyjama commands.
    children:
      pyjama.command.info: true
      pyjama.command.reload: true
  pyjama.command.info:
    description: Allows using the /pyjama command to view plugin info.
  pyjama.command.reload:
    description: Allows reloading Pyjama configuration.